name: multimeter-env
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.11
  - ipykernel
  - scipy
  - numpy
  - matplotlib
  - gitpython
prefix: /home/matias/miniconda3/envs/multimeter-env
